on:
  - push
  - workflow_dispatch
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}


      #  - name: Build app
      #     run: npm install && npm run build

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          PRIVATE_SECRET: "op://cicd/dg_github/private key?ssh-format=openssh"
          ENV_FILE: "op://cicd/Secure Note/text"

      - name: Create env file
        run: echo '${{ steps.op-load-secret.outputs.ENV_FILE }}' > .env

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ steps.op-load-secret.outputs.PRIVATE_SECRET }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_OF_TARGET }}

      - name: Build
        run: npm install && npm run build

      - name: Run rsync
        run: rsync --relative -avz  ./ root@${{ secrets.SERVER_URL }}:~/discord-repost-bot

      - name: Run SSH Command
        run: ssh root@${{ secrets.SERVER_URL }} -f 'source ~/.nvm/nvm.sh && cd discord-repost-bot && pm2 restart discord-repost-bot'
